// API KEY : 3ca5df7
export const data = [
  {
    Title: "The Avengers",
    Year: "2012",
    Rated: "PG-13",
    Released: "04 May 2012",
    Runtime: "143 min",
    Genre: "Action, Adventure, Sci-Fi",
    Director: "Joss Whedon",
    Writer: "Joss Whedon (screenplay), Zak Penn (story), Joss Whedon (story)",
    Actors: "Robert Downey Jr., Chris Evans, Mark Ruffalo, Chris Hemsworth",
    Plot: "Earth's mightiest heroes must come together and learn to fight as a team if they are going to stop the mischievous Loki and his alien army from enslaving humanity.",
    Language: "English, Russian, Hindi",
    Country: "USA",
    Awards: "Nominated for 1 Oscar. Another 38 wins & 79 nominations.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNDYxNjQyMjAtNTdiOS00NGYwLWFmNTAtNThmYjU5ZGI2YTI1XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "8.0/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "91%",
      },
      {
        Source: "Metacritic",
        Value: "69/100",
      },
    ],
    Metascore: "69",
    imdbRating: "8.0",
    imdbVotes: "1,216,895",
    imdbID: "tt0848228",
    Type: "movie",
    DVD: "25 Sep 2012",
    BoxOffice: "$623,279,547",
    Production: "Walt Disney Pictures",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Justice League",
    Year: "2017",
    Rated: "PG-13",
    Released: "17 Nov 2017",
    Runtime: "120 min",
    Genre: "Action, Adventure, Fantasy, Sci-Fi",
    Director: "Zack Snyder",
    Writer:
      "Jerry Siegel (Superman created by), Joe Shuster (Superman created by), Chris Terrio (story by), Zack Snyder (story by), Chris Terrio (screenplay by), Joss Whedon (screenplay by), Gardner Fox (Justice League of America created by), Bob Kane (Batman created by), Bill Finger (Batman created by), William Moulton Marston (Wonder Woman created by), Jack Kirby (Fourth World created by)",
    Actors: "Ben Affleck, Henry Cavill, Amy Adams, Gal Gadot",
    Plot: "Fueled by his restored faith in humanity and inspired by Superman's selfless act, Bruce Wayne enlists the help of his new-found ally, Diana Prince, to face an even greater enemy.",
    Language: "Irish, Russian, Icelandic, English",
    Country: "USA, Canada, UK",
    Awards: "2 wins & 13 nominations.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BYWVhZjZkYTItOGIwYS00NmRkLWJlYjctMWM0ZjFmMDU4ZjEzXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "6.2/10" },
      { Source: "Rotten Tomatoes", Value: "40%" },
      { Source: "Metacritic", Value: "45/100" },
    ],
    Metascore: "45",
    imdbRating: "6.2",
    imdbVotes: "413,900",
    imdbID: "tt0974015",
    Type: "movie",
    DVD: "13 Feb 2018",
    BoxOffice: "$229,024,295",
    Production: "Atlas Entertainment, Cruel and Unusual",
    Website: "N/A",
    Response: "True",
  },

  {
    Title: "Blade",
    Year: "1998",
    Rated: "R",
    Released: "21 Aug 1998",
    Runtime: "120 min",
    Genre: "Action, Horror, Sci-Fi",
    Director: "Stephen Norrington",
    Writer: "David S. Goyer",
    Actors: "Wesley Snipes, Stephen Dorff, Kris Kristofferson, N'Bushe Wright",
    Plot: "A half-vampire, half-mortal man becomes a protector of the mortal race, while slaying evil vampires.",
    Language: "English, Russian, Serbian",
    Country: "USA",
    Awards: "5 wins & 11 nominations.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BOTk2NDNjZWQtMGY0Mi00YTY2LWE5MzctMGRhZmNlYzljYTg5XkEyXkFqcGdeQXVyMTAyNjg4NjE0._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "7.1/10" },
      { Source: "Rotten Tomatoes", Value: "55%" },
      { Source: "Metacritic", Value: "45/100" },
    ],
    Metascore: "45",
    imdbRating: "7.1",
    imdbVotes: "249,692",
    imdbID: "tt0120611",
    Type: "movie",
    DVD: "11 Sep 2015",
    BoxOffice: "$70,087,718",
    Production: "New Line Cinema, Imaginary Forces, Amen Ra Films",
    Website: "N/A",
    Response: "True",
  },

  {
    Title: "The Dark Knight",
    Year: "2008",
    Rated: "PG-13",
    Released: "18 Jul 2008",
    Runtime: "152 min",
    Genre: "Action, Crime, Drama, Thriller",
    Director: "Christopher Nolan",
    Writer:
      "Jonathan Nolan (screenplay), Christopher Nolan (screenplay), Christopher Nolan (story), David S. Goyer (story), Bob Kane (characters)",
    Actors: "Christian Bale, Heath Ledger, Aaron Eckhart, Michael Caine",
    Plot: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    Language: "English, Mandarin",
    Country: "USA, UK",
    Awards: "Won 2 Oscars. Another 153 wins & 159 nominations.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "9.0/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "94%",
      },
      {
        Source: "Metacritic",
        Value: "84/100",
      },
    ],
    Metascore: "84",
    imdbRating: "9.0",
    imdbVotes: "2,173,344",
    imdbID: "tt0468569",
    Type: "movie",
    DVD: "09 Dec 2008",
    BoxOffice: "$533,316,061",
    Production: "Warner Bros. Pictures/Legendary",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "The Social Network",
    Year: "2010",
    Rated: "PG-13",
    Released: "01 Oct 2010",
    Runtime: "120 min",
    Genre: "Biography, Drama",
    Director: "David Fincher",
    Writer: "Aaron Sorkin (screenplay), Ben Mezrich (book)",
    Actors: "Jesse Eisenberg, Rooney Mara, Bryan Barter, Dustin Fitzsimons",
    Plot: "As Harvard student Mark Zuckerberg creates the social networking site that would become known as Facebook, he is sued by the twins who claimed he stole their idea, and by the co-founder who was later squeezed out of the business.",
    Language: "English, French",
    Country: "USA",
    Awards: "Won 3 Oscars. Another 169 wins & 186 nominations.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BOGUyZDUxZjEtMmIzMC00MzlmLTg4MGItZWJmMzBhZjE0Mjc1XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "7.7/10" },
      { Source: "Rotten Tomatoes", Value: "96%" },
      { Source: "Metacritic", Value: "95/100" },
    ],
    Metascore: "95",
    imdbRating: "7.7",
    imdbVotes: "638,542",
    imdbID: "tt1285016",
    Type: "movie",
    DVD: "05 Jun 2012",
    BoxOffice: "$96,962,694",
    Production:
      "Scott Rudin Productions, Trigger Street Productions, Michael De Luca",
    Website: "N/A",
    Response: "True",
  },

  {
    Title: "Tenet",
    Year: "2020",
    Rated: "PG-13",
    Released: "03 Sep 2020",
    Runtime: "150 min",
    Genre: "Action, Sci-Fi, Thriller",
    Director: "Christopher Nolan",
    Writer: "Christopher Nolan",
    Actors: "Juhan Ulfsak, Jefferson Hall, Ivo Uukkivi, Andrew Howard",
    Plot: "Armed with only one word, Tenet, and fighting for the survival of the entire world, a Protagonist journeys through a twilight world of international espionage on a mission that will unfold in something beyond real time.",
    Language: "English, Russian, Ukrainian, Estonian, Norwegian, Hindi",
    Country: "UK, USA",
    Awards: "Won 1 Oscar. Another 40 wins & 131 nominations.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BYzg0NGM2NjAtNmIxOC00MDJmLTg5ZmYtYzM0MTE4NWE2NzlhXkEyXkFqcGdeQXVyMTA4NjE0NjEy._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "7.4/10" },
      { Source: "Rotten Tomatoes", Value: "70%" },
      { Source: "Metacritic", Value: "69/100" },
    ],
    Metascore: "69",
    imdbRating: "7.4",
    imdbVotes: "351,925",
    imdbID: "tt6723592",
    Type: "movie",
    DVD: "15 Dec 2020",
    BoxOffice: "$58,456,624",
    Production: "Syncopy, Warner Bros. Pictures",
    Website: "N/A",
    Response: "True",
  },

  {
    Title: "Iron Man",
    Year: "2008",
    Rated: "PG-13",
    Released: "02 May 2008",
    Runtime: "126 min",
    Genre: "Action, Adventure, Sci-Fi",
    Director: "Jon Favreau",
    Writer:
      "Mark Fergus (screenplay), Hawk Ostby (screenplay), Art Marcum (screenplay), Matt Holloway (screenplay), Stan Lee (characters), Don Heck (characters), Larry Lieber (characters), Jack Kirby (characters)",
    Actors: "Robert Downey Jr., Terrence Howard, Jeff Bridges, Gwyneth Paltrow",
    Plot: "After being held captive in an Afghan cave, billionaire engineer Tony Stark creates a unique weaponized suit of armor to fight evil.",
    Language: "Hungarian, Kurdish, Hindi, English, Persian, Urdu, Arabic",
    Country: "USA",
    Awards: "Nominated for 2 Oscars. Another 21 wins & 65 nominations.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMTczNTI2ODUwOF5BMl5BanBnXkFtZTcwMTU0NTIzMw@@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "7.9/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "94%",
      },
      {
        Source: "Metacritic",
        Value: "79/100",
      },
    ],
    Metascore: "79",
    imdbRating: "7.9",
    imdbVotes: "896,884",
    imdbID: "tt0371746",
    Type: "movie",
    DVD: "30 Sep 2008",
    BoxOffice: "$318,298,180",
    Production: "Paramount Pictures",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Inception",
    Year: "2010",
    Rated: "PG-13",
    Released: "16 Jul 2010",
    Runtime: "148 min",
    Genre: "Action, Adventure, Sci-Fi, Thriller",
    Director: "Christopher Nolan",
    Writer: "Christopher Nolan",
    Actors: "Leonardo DiCaprio, Joseph Gordon-Levitt, Elliot Page, Tom Hardy",
    Plot: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
    Language: "English, Japanese, French",
    Country: "USA, UK",
    Awards: "Won 4 Oscars. Another 153 wins & 220 nominations.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "8.8/10" },
      { Source: "Rotten Tomatoes", Value: "87%" },
      { Source: "Metacritic", Value: "74/100" },
    ],
    Metascore: "74",
    imdbRating: "8.8",
    imdbVotes: "2,112,329",
    imdbID: "tt1375666",
    Type: "movie",
    DVD: "20 Jun 2013",
    BoxOffice: "$292,576,195",
    Production: "Syncopy, Warner Bros.",
    Website: "N/A",
    Response: "True",
  },

  {
    Title: "Dunkirk",
    Year: "2017",
    Rated: "PG-13",
    Released: "21 Jul 2017",
    Runtime: "106 min",
    Genre: "Action, Drama, History, Thriller, War",
    Director: "Christopher Nolan",
    Writer: "Christopher Nolan",
    Actors: "Fionn Whitehead, Damien Bonnard, Aneurin Barnard, Lee Armstrong",
    Plot: "Allied soldiers from Belgium, the British Commonwealth and Empire, and France are surrounded by the German Army and evacuated during a fierce battle in World War II.",
    Language: "English, French, German",
    Country: "UK, Netherlands, France, USA",
    Awards: "Won 3 Oscars. Another 60 wins & 230 nominations.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BN2YyZjQ0NTEtNzU5MS00NGZkLTg0MTEtYzJmMWY3MWRhZjM2XkEyXkFqcGdeQXVyMDA4NzMyOA@@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "7.8/10" },
      { Source: "Rotten Tomatoes", Value: "92%" },
      { Source: "Metacritic", Value: "94/100" },
    ],
    Metascore: "94",
    imdbRating: "7.8",
    imdbVotes: "572,711",
    imdbID: "tt5013056",
    Type: "movie",
    DVD: "12 Dec 2017",
    BoxOffice: "$189,740,665",
    Production: "Warner Bros. Pictures, IMAX Corporation",
    Website: "N/A",
    Response: "True",
  },

  {
    Title: "Conjuring",
    Year: "1896",
    Rated: "N/A",
    Released: "N/A",
    Runtime: "N/A",
    Genre: "Short",
    Director: "Georges Méliès",
    Writer: "N/A",
    Actors: "Georges Méliès",
    Plot: "Boognish the goddemon Wants your soul to perform tricks for him. WEEN is your only salvation.",
    Language: "None",
    Country: "France",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BZDcwOWExZGYtMzk3Mi00ODczLWE3MTQtNGRhNjMyMTBlMGY1XkEyXkFqcGdeQXVyNzUyMjQ3NTQ@._V1_SX300.jpg",
    Ratings: [{ Source: "Internet Movie Database", Value: "5.7/10" }],
    Metascore: "N/A",
    imdbRating: "5.7",
    imdbVotes: "80",
    imdbID: "tt0000123",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },

  {
    Title: "Aquaman",
    Year: "2018",
    Rated: "PG-13",
    Released: "21 Dec 2018",
    Runtime: "143 min",
    Genre: "Action, Adventure, Fantasy, Sci-Fi",
    Director: "James Wan",
    Writer:
      "David Leslie Johnson-McGoldrick (screenplay by), Will Beall (screenplay by), Geoff Johns (story by), James Wan (story by), Will Beall (story by), Paul Norris (Aquaman created by), Mort Weisinger (Aquaman created by)",
    Actors: "Jason Momoa, Amber Heard, Willem Dafoe, Patrick Wilson",
    Plot: "Arthur Curry, the human-born heir to the underwater kingdom of Atlantis, goes on a quest to prevent a war between the worlds of ocean and land.",
    Language: "English, Russian, Maori, Italian",
    Country: "USA, Australia",
    Awards: "2 wins & 39 nominations.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BOTk5ODg0OTU5M15BMl5BanBnXkFtZTgwMDQ3MDY3NjM@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "6.9/10" },
      { Source: "Rotten Tomatoes", Value: "65%" },
      { Source: "Metacritic", Value: "55/100" },
    ],
    Metascore: "55",
    imdbRating: "6.9",
    imdbVotes: "394,687",
    imdbID: "tt1477834",
    Type: "movie",
    DVD: "05 Mar 2019",
    BoxOffice: "$335,061,807",
    Production: "Peter Safran",
    Website: "N/A",
    Response: "True",
  },

  {
    Title: "Wonder Woman",
    Year: "2017",
    Rated: "PG-13",
    Released: "02 Jun 2017",
    Runtime: "141 min",
    Genre: "Action, Adventure, Fantasy, Sci-Fi, War",
    Director: "Patty Jenkins",
    Writer:
      "Allan Heinberg (screenplay by), Zack Snyder (story by), Allan Heinberg (story by), Jason Fuchs (story by), William Moulton Marston (Wonder Woman created by)",
    Actors: "Gal Gadot, Chris Pine, Connie Nielsen, Robin Wright",
    Plot: "When a pilot crashes and tells of conflict in the outside world, Diana, an Amazonian warrior in training, leaves home to fight a war, discovering her full powers and true destiny.",
    Language:
      "English, German, Dutch, French, Spanish, Chinese, Greek, Ancient (to 1453), North American Indian",
    Country: "USA, UK",
    Awards: "26 wins & 72 nominations.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMTYzODQzYjQtNTczNC00MzZhLTg1ZWYtZDUxYmQ3ZTY4NzA1XkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "7.4/10" },
      { Source: "Rotten Tomatoes", Value: "93%" },
      { Source: "Metacritic", Value: "76/100" },
    ],
    Metascore: "76",
    imdbRating: "7.4",
    imdbVotes: "592,279",
    imdbID: "tt0451279",
    Type: "movie",
    DVD: "10 Jul 2017",
    BoxOffice: "$412,815,408",
    Production: "Atlas Entertainment, Cruel and Unusual",
    Website: "N/A",
    Response: "True",
  },

  {
    Title: "Transformers",
    Year: "2007",
    Rated: "PG-13",
    Released: "03 Jul 2007",
    Runtime: "144 min",
    Genre: "Action, Adventure, Sci-Fi",
    Director: "Michael Bay",
    Writer: "Roberto Orci, Alex Kurtzman, John Rogers",
    Actors: "Shia LaBeouf, Megan Fox, Josh Duhamel",
    Plot: "An ancient struggle between two Cybertronian races, the heroic Autobots and the evil Decepticons, comes to Earth, with a clue to the ultimate power held by a teenager.",
    Language: "English, Spanish",
    Country: "United States",
    Awards: "Nominated for 3 Oscars. 25 wins & 50 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNDg1NTU2OWEtM2UzYi00ZWRmLWEwMTktZWNjYWQ1NWM1OThjXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "7.0/10" },
      { Source: "Rotten Tomatoes", Value: "58%" },
      { Source: "Metacritic", Value: "61/100" },
    ],
    Metascore: "61",
    imdbRating: "7.0",
    imdbVotes: "603,405",
    imdbID: "tt0418279",
    Type: "movie",
    DVD: "06 Jun 2014",
    BoxOffice: "$319,246,193",
    Production:
      "DreamWorks SKG, Paramount Pictures International, Di Bonaventura Pictures",
    Website: "N/A",
    Response: "True",
  },

  {
    Title: "Iron Man 2",
    Year: "2010",
    Rated: "PG-13",
    Released: "07 May 2010",
    Runtime: "124 min",
    Genre: "Action, Adventure, Sci-Fi",
    Director: "Jon Favreau",
    Writer:
      "Justin Theroux (screenplay), Stan Lee (Marvel comic book), Don Heck (Marvel comic book), Larry Lieber (Marvel comic book), Jack Kirby (Marvel comic book)",
    Actors:
      "Robert Downey Jr., Gwyneth Paltrow, Don Cheadle, Scarlett Johansson",
    Plot: "With the world now aware of his identity as Iron Man, Tony Stark must contend with both his declining health and a vengeful mad man with ties to his father's legacy.",
    Language: "English, French, Russian",
    Country: "USA",
    Awards: "Nominated for 1 Oscar. Another 7 wins & 43 nominations.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMTM0MDgwNjMyMl5BMl5BanBnXkFtZTcwNTg3NzAzMw@@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "7.0/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "73%",
      },
      {
        Source: "Metacritic",
        Value: "57/100",
      },
    ],
    Metascore: "57",
    imdbRating: "7.0",
    imdbVotes: "686,304",
    imdbID: "tt1228705",
    Type: "movie",
    DVD: "28 Sep 2010",
    BoxOffice: "$312,057,433",
    Production: "Paramount Studios",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Source Code",
    Year: "2011",
    Rated: "PG-13",
    Released: "01 Apr 2011",
    Runtime: "93 min",
    Genre: "Action, Drama, Mystery, Sci-Fi, Thriller",
    Director: "Duncan Jones",
    Writer: "Ben Ripley",
    Actors: "Jake Gyllenhaal, Michelle Monaghan, Vera Farmiga, Jeffrey Wright",
    Plot: "A soldier wakes up in someone else's body and discovers he's part of an experimental government program to find the bomber of a commuter train within 8 minutes.",
    Language: "English",
    Country: "USA, Canada, France, Germany",
    Awards: "1 win & 8 nominations.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMTY0MTc3MzMzNV5BMl5BanBnXkFtZTcwNDE4MjE0NA@@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "7.5/10" },
      { Source: "Rotten Tomatoes", Value: "92%" },
      { Source: "Metacritic", Value: "74/100" },
    ],
    Metascore: "74",
    imdbRating: "7.5",
    imdbVotes: "491,033",
    imdbID: "tt0945513",
    Type: "movie",
    DVD: "20 Dec 2015",
    BoxOffice: "$54,712,227",
    Production: "Mark Gordon Productions",
    Website: "N/A",
    Response: "True",
  },

  {
    Title: "Iron Man 3",
    Year: "2013",
    Rated: "PG-13",
    Released: "03 May 2013",
    Runtime: "130 min",
    Genre: "Action, Adventure, Sci-Fi",
    Director: "Shane Black",
    Writer:
      'Drew Pearce (screenplay by), Shane Black (screenplay by), Stan Lee (based on the Marvel comic book by), Don Heck (based on the Marvel comic book by), Larry Lieber (based on the Marvel comic book by), Jack Kirby (based on the Marvel comic book by), Warren Ellis (based on the "Extremis" mini-series written by), Adi Granov (based on the "Extremis" mini-series illustrated by)',
    Actors: "Robert Downey Jr., Gwyneth Paltrow, Don Cheadle, Guy Pearce",
    Plot: "When Tony Stark's world is torn apart by a formidable terrorist called the Mandarin, he starts an odyssey of rebuilding and retribution.",
    Language: "English",
    Country: "USA",
    Awards: "Nominated for 1 Oscar. Another 20 wins & 62 nominations.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMjE5MzcyNjk1M15BMl5BanBnXkFtZTcwMjQ4MjcxOQ@@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "7.2/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "79%",
      },
      {
        Source: "Metacritic",
        Value: "62/100",
      },
    ],
    Metascore: "62",
    imdbRating: "7.2",
    imdbVotes: "719,976",
    imdbID: "tt1300854",
    Type: "movie",
    DVD: "24 Sep 2013",
    BoxOffice: "$408,992,272",
    Production: "Walt Disney Pictures",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Die Hard",
    Year: "1988",
    Rated: "R",
    Released: "20 Jul 1988",
    Runtime: "132 min",
    Genre: "Action, Thriller",
    Director: "John McTiernan",
    Writer:
      "Roderick Thorp (based on the novel by), Jeb Stuart (screenplay by), Steven E. de Souza (screenplay by)",
    Actors: "Bruce Willis, Bonnie Bedelia, Reginald VelJohnson, Paul Gleason",
    Plot: "An NYPD officer tries to save his wife and several others taken hostage by German terrorists during a Christmas party at the Nakatomi Plaza in Los Angeles.",
    Language: "English, German, Italian, Japanese",
    Country: "USA",
    Awards: "Nominated for 4 Oscars. Another 8 wins & 2 nominations.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BZjRlNDUxZjAtOGQ4OC00OTNlLTgxNmQtYTBmMDgwZmNmNjkxXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "8.2/10" },
      { Source: "Rotten Tomatoes", Value: "94%" },
      { Source: "Metacritic", Value: "72/100" },
    ],
    Metascore: "72",
    imdbRating: "8.2",
    imdbVotes: "804,213",
    imdbID: "tt0095016",
    Type: "movie",
    DVD: "25 Nov 2015",
    BoxOffice: "$83,844,093",
    Production: "Silver Pictures, Gordon Company",
    Website: "N/A",
    Response: "True",
  },

  {
    Title: "Back to the Future",
    Year: "1985",
    Rated: "PG",
    Released: "03 Jul 1985",
    Runtime: "116 min",
    Genre: "Adventure, Comedy, Sci-Fi",
    Director: "Robert Zemeckis",
    Writer: "Robert Zemeckis, Bob Gale",
    Actors: "Michael J. Fox, Christopher Lloyd, Lea Thompson, Crispin Glover",
    Plot: "Marty McFly, a 17-year-old high school student, is accidentally sent thirty years into the past in a time-traveling DeLorean invented by his close friend, the eccentric scientist Doc Brown.",
    Language: "English",
    Country: "USA",
    Awards: "Won 1 Oscar. Another 22 wins & 25 nominations.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BZmU0M2Y1OGUtZjIxNi00ZjBkLTg1MjgtOWIyNThiZWIwYjRiXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "8.5/10" },
      { Source: "Rotten Tomatoes", Value: "96%" },
      { Source: "Metacritic", Value: "87/100" },
    ],
    Metascore: "87",
    imdbRating: "8.5",
    imdbVotes: "1,080,991",
    imdbID: "tt0088763",
    Type: "movie",
    DVD: "08 Aug 2013",
    BoxOffice: "$211,406,762",
    Production: "Universal Pictures, Amblin Entertainment",
    Website: "N/A",
    Response: "True",
  },

  {
    Title: "The Day After Tomorrow",
    Year: "2004",
    Rated: "PG-13",
    Released: "28 May 2004",
    Runtime: "124 min",
    Genre: "Action, Adventure, Sci-Fi, Thriller",
    Director: "Roland Emmerich",
    Writer:
      "Roland Emmerich (story), Roland Emmerich (screenplay), Jeffrey Nachmanoff (screenplay)",
    Actors: "Dennis Quaid, Jake Gyllenhaal, Emmy Rossum, Dash Mihok",
    Plot: "Jack Hall, paleoclimatologist, must make a daring trek from Washington, D.C. to New York City to reach his son, trapped in the cross-hairs of a sudden international storm which plunges the planet into a new Ice Age.",
    Language: "English, Japanese, French, Arabic",
    Country: "USA",
    Awards: "Won 1 BAFTA Film Award. Another 5 wins & 12 nominations.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMTM3NDU4NDA2Ml5BMl5BanBnXkFtZTYwNzcxNjY2._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "6.4/10" },
      { Source: "Rotten Tomatoes", Value: "45%" },
      { Source: "Metacritic", Value: "47/100" },
    ],
    Metascore: "47",
    imdbRating: "6.4",
    imdbVotes: "420,822",
    imdbID: "tt0319262",
    Type: "movie",
    DVD: "25 Nov 2015",
    BoxOffice: "$186,740,799",
    Production:
      "Centropolis Film Productions, Tomorrow Films, Mark Gordon Productions",
    Website: "N/A",
    Response: "True",
  },

  {
    Title: "Ronaldo",
    Year: "2015",
    Rated: "PG-13",
    Released: "09 Nov 2015",
    Runtime: "92 min",
    Genre: "Documentary, Biography, Sport",
    Director: "Anthony Wonke",
    Writer: "N/A",
    Actors: "Dolores Aveiro, Hugo Aveiro, Georgie Bingham, Adrian Clarke",
    Plot: "A close look at the life of Cristiano Ronaldo.",
    Language: "Portuguese, English, Spanish",
    Country: "UK, Spain",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNzMyMTM1MjQxNF5BMl5BanBnXkFtZTgwMjY4NTE5NjE@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "6.4/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "17%",
      },
    ],
    Metascore: "N/A",
    imdbRating: "6.4",
    imdbVotes: "13,549",
    imdbID: "tt5065822",
    Type: "movie",
    DVD: "10 Nov 2015",
    BoxOffice: "N/A",
    Production: "On The Corner Films",
    Website: "http://www.ronaldothefilm.com/showtimes",
    Response: "True",
  },
  {
    Title: "Thor",
    Year: "2011",
    Rated: "PG-13",
    Released: "06 May 2011",
    Runtime: "115 min",
    Genre: "Action, Adventure, Fantasy",
    Director: "Kenneth Branagh",
    Writer:
      "Ashley Miller (screenplay), Zack Stentz (screenplay), Don Payne (screenplay), J. Michael Straczynski (story), Mark Protosevich (story), Stan Lee (comic book), Larry Lieber (comic book), Jack Kirby (comic book)",
    Actors: "Chris Hemsworth, Natalie Portman, Tom Hiddleston, Anthony Hopkins",
    Plot: "The powerful but arrogant god Thor is cast out of Asgard to live amongst humans in Midgard (Earth), where he soon becomes one of their finest defenders.",
    Language: "English",
    Country: "USA",
    Awards: "5 wins & 30 nominations.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BOGE4NzU1YTAtNzA3Mi00ZTA2LTg2YmYtMDJmMThiMjlkYjg2XkEyXkFqcGdeQXVyNTgzMDMzMTg@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "7.0/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "77%",
      },
      {
        Source: "Metacritic",
        Value: "57/100",
      },
    ],
    Metascore: "57",
    imdbRating: "7.0",
    imdbVotes: "710,805",
    imdbID: "tt0800369",
    Type: "movie",
    DVD: "13 Sep 2011",
    BoxOffice: "$181,015,141",
    Production: "Paramount Pictures",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Superman",
    Year: "1978",
    Rated: "PG",
    Released: "15 Dec 1978",
    Runtime: "143 min",
    Genre: "Action, Adventure, Drama, Sci-Fi",
    Director: "Richard Donner",
    Writer:
      "Jerry Siegel (character created by: Superman), Joe Shuster (character created by: Superman), Mario Puzo (story), Mario Puzo (screenplay), David Newman (screenplay), Leslie Newman (screenplay), Robert Benton (screenplay)",
    Actors: "Marlon Brando, Gene Hackman, Christopher Reeve, Ned Beatty",
    Plot: "An alien orphan is sent from his dying planet to Earth, where he grows up to become his adoptive home's first and greatest superhero.",
    Language: "English",
    Country: "USA, UK, Canada, Switzerland, France",
    Awards: "Nominated for 3 Oscars. Another 18 wins & 20 nominations.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMzA0YWMwMTUtMTVhNC00NjRkLWE2ZTgtOWEzNjJhYzNiMTlkXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "7.3/10" },
      { Source: "Rotten Tomatoes", Value: "94%" },
      { Source: "Metacritic", Value: "80/100" },
    ],
    Metascore: "80",
    imdbRating: "7.3",
    imdbVotes: "161,675",
    imdbID: "tt0078346",
    Type: "movie",
    DVD: "15 Aug 2008",
    BoxOffice: "$134,451,603",
    Production: "Dovemead Films",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Jumanji",
    Year: "1995",
    Rated: "PG",
    Released: "15 Dec 1995",
    Runtime: "104 min",
    Genre: "Adventure, Comedy, Family, Fantasy",
    Director: "Joe Johnston",
    Writer:
      "Jonathan Hensleigh (screenplay by), Greg Taylor (screenplay by), Jim Strain (screenplay by), Greg Taylor (screen story by), Jim Strain (screen story by), Chris Van Allsburg (screen story by), Chris Van Allsburg (based on the book by)",
    Actors: "Robin Williams, Jonathan Hyde, Kirsten Dunst, Bradley Pierce",
    Plot: "When two kids find and play a magical board game, they release a man trapped in it for decades - and a host of dangers that can only be stopped by finishing the game.",
    Language: "English, French",
    Country: "USA",
    Awards: "4 wins & 11 nominations.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BZTk2ZmUwYmEtNTcwZS00YmMyLWFkYjMtNTRmZDA3YWExMjc2XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "7.0/10" },
      { Source: "Rotten Tomatoes", Value: "55%" },
      { Source: "Metacritic", Value: "39/100" },
    ],
    Metascore: "39",
    imdbRating: "7.0",
    imdbVotes: "314,983",
    imdbID: "tt0113497",
    Type: "movie",
    DVD: "02 Sep 2003",
    BoxOffice: "$100,499,940",
    Production: "TriStar Pictures, Interscope Communications",
    Website: "N/A",
    Response: "True",
  },

  {
    Title: "Thor: The Dark World",
    Year: "2013",
    Rated: "PG-13",
    Released: "08 Nov 2013",
    Runtime: "112 min",
    Genre: "Action, Adventure, Fantasy",
    Director: "Alan Taylor",
    Writer:
      "Christopher L. Yost (screenplay by), Christopher Markus (screenplay by), Stephen McFeely (screenplay by), Don Payne (story by), Robert Rodat (story by), Stan Lee (based on the Marvel comics by), Larry Lieber (based on the Marvel comics by), Jack Kirby (based on the Marvel comics by), Walter Simonson (character created by: Malekith)",
    Actors: "Chris Hemsworth, Natalie Portman, Tom Hiddleston, Anthony Hopkins",
    Plot: "When the Dark Elves attempt to plunge the universe into darkness, Thor must embark on a perilous and personal journey that will reunite him with doctor Jane Foster.",
    Language: "English",
    Country: "USA",
    Awards: "3 wins & 21 nominations.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMTQyNzAwOTUxOF5BMl5BanBnXkFtZTcwMTE0OTc5OQ@@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "6.9/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "66%",
      },
      {
        Source: "Metacritic",
        Value: "54/100",
      },
    ],
    Metascore: "54",
    imdbRating: "6.9",
    imdbVotes: "564,401",
    imdbID: "tt1981115",
    Type: "movie",
    DVD: "25 Feb 2014",
    BoxOffice: "$206,360,018",
    Production: "Walt Disney Pictures",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Thor: Ragnarok",
    Year: "2017",
    Rated: "PG-13",
    Released: "03 Nov 2017",
    Runtime: "130 min",
    Genre: "Action, Adventure, Comedy, Fantasy, Sci-Fi",
    Director: "Taika Waititi",
    Writer:
      "Eric Pearson, Craig Kyle, Christopher L. Yost, Stan Lee (based on the Marvel comics by), Larry Lieber (based on the Marvel comics by), Jack Kirby (based on the Marvel comics by)",
    Actors: "Chris Hemsworth, Tom Hiddleston, Cate Blanchett, Idris Elba",
    Plot: "Imprisoned on the planet Sakaar, Thor must race against time to return to Asgard and stop Ragnarök, the destruction of his world, at the hands of the powerful and ruthless villain Hela.",
    Language: "English",
    Country: "USA",
    Awards: "6 wins & 48 nominations.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMjMyNDkzMzI1OF5BMl5BanBnXkFtZTgwODcxODg5MjI@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "7.9/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "93%",
      },
      {
        Source: "Metacritic",
        Value: "74/100",
      },
    ],
    Metascore: "74",
    imdbRating: "7.9",
    imdbVotes: "532,010",
    imdbID: "tt3501632",
    Type: "movie",
    DVD: "06 Mar 2018",
    BoxOffice: "$314,971,245",
    Production: "Walt Disney Pictures",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Avengers: Infinity War",
    Year: "2018",
    Rated: "PG-13",
    Released: "27 Apr 2018",
    Runtime: "149 min",
    Genre: "Action, Adventure, Sci-Fi",
    Director: "Anthony Russo, Joe Russo",
    Writer:
      "Christopher Markus (screenplay by), Stephen McFeely (screenplay by), Stan Lee (based on the Marvel comics by), Jack Kirby (based on the Marvel comics by), Joe Simon (Captain America created by), Jack Kirby (Captain America created by), Steve Englehart (Star-Lord created by), Steve Gan (Star-Lord created by), Bill Mantlo (Rocket Raccoon created by), Keith Giffen (Rocket Raccoon created by), Jim Starlin (Thanos,  Gamora and Drax created by), Stan Lee (Groot created by), Larry Lieber (Groot created by), Jack Kirby (Groot created by), Steve Englehart (Mantis created by), Don Heck (Mantis created by)",
    Actors: "Robert Downey Jr., Chris Hemsworth, Mark Ruffalo, Chris Evans",
    Plot: "The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos before his blitz of devastation and ruin puts an end to the universe.",
    Language: "English",
    Country: "USA",
    Awards: "Nominated for 1 Oscar. Another 44 wins & 70 nominations.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMjMxNjY2MDU1OV5BMl5BanBnXkFtZTgwNzY1MTUwNTM@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "8.5/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "85%",
      },
      {
        Source: "Metacritic",
        Value: "68/100",
      },
    ],
    Metascore: "68",
    imdbRating: "8.5",
    imdbVotes: "748,996",
    imdbID: "tt4154756",
    Type: "movie",
    DVD: "14 Aug 2018",
    BoxOffice: "$664,987,816",
    Production: "Walt Disney Pictures",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Avengers: Endgame",
    Year: "2019",
    Rated: "PG-13",
    Released: "26 Apr 2019",
    Runtime: "181 min",
    Genre: "Action, Adventure, Drama, Sci-Fi",
    Director: "Anthony Russo, Joe Russo",
    Writer:
      "Christopher Markus (screenplay by), Stephen McFeely (screenplay by), Stan Lee (based on the Marvel comics by), Jack Kirby (based on the Marvel comics by), Joe Simon (Captain America created by), Jack Kirby (Captain America created by), Steve Englehart (Star-Lord created by), Steve Gan (Star-Lord created by), Bill Mantlo (Rocket Raccoon created by), Keith Giffen (Rocket Raccoon created by), Jim Starlin (Thanos,  Gamora & Drax created by), Stan Lee (Groot created by), Larry Lieber (Groot created by), Jack Kirby (Groot created by), Steve Englehart (Mantis created by), Don Heck (Mantis created by)",
    Actors: "Robert Downey Jr., Chris Evans, Mark Ruffalo, Chris Hemsworth",
    Plot: "After the devastating events of Avengers: Infinity War (2018), the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.",
    Language: "English, Japanese, Xhosa, German",
    Country: "USA",
    Awards: "Nominated for 1 Oscar. Another 46 wins & 97 nominations.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMTc5MDE2ODcwNV5BMl5BanBnXkFtZTgwMzI2NzQ2NzM@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "8.5/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "94%",
      },
      {
        Source: "Metacritic",
        Value: "78/100",
      },
    ],
    Metascore: "78",
    imdbRating: "8.5",
    imdbVotes: "661,719",
    imdbID: "tt4154796",
    Type: "movie",
    DVD: "30 Jul 2019",
    BoxOffice: "N/A",
    Production: "Marvel Studios",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Man of Steel",
    Year: "2013",
    Rated: "PG-13",
    Released: "14 Jun 2013",
    Runtime: "143 min",
    Genre: "Action, Adventure, Sci-Fi",
    Director: "Zack Snyder",
    Writer:
      "David S. Goyer (screenplay), David S. Goyer (story), Christopher Nolan (story), Jerry Siegel (Superman created by), Joe Shuster (Superman created by)",
    Actors: "Henry Cavill, Amy Adams, Michael Shannon, Diane Lane",
    Plot: "An alien child is evacuated from his dying world and sent to Earth to live among humans. His peace is threatened, when survivors of his home planet invade Earth.",
    Language: "English",
    Country: "USA, UK",
    Awards: "7 wins & 46 nominations.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMTk5ODk1NDkxMF5BMl5BanBnXkFtZTcwNTA5OTY0OQ@@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "7.1/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "56%",
      },
      {
        Source: "Metacritic",
        Value: "55/100",
      },
    ],
    Metascore: "55",
    imdbRating: "7.1",
    imdbVotes: "664,610",
    imdbID: "tt0770828",
    Type: "movie",
    DVD: "12 Nov 2013",
    BoxOffice: "$291,021,565",
    Production: "Warner Bros. Pictures",
    Website: "N/A",
    Response: "True",
  },
];
